apiVersion: batch/v1
kind: Job
metadata:
  name: test-run-single-oddservicetest
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
        - name: c
          image: tom-collings/parallel-testing:1.0
          command: ["sh", "-c", "./gradlew test -x classes -x testClasses --offline --tests com.example.parallel.service.OddServiceTest"]
      restartPolicy: Never
